spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

payment:
  toss:
    test_client_key: "test_ck_6BYq7GWPVv5DRddeYNn3NE5vbo1d"
    test_secret_key: "test_sk_eqRGgYO1r5qOd0v64nWrQnN2Eyaz"
    success_url: "http://localhost:8080/api/v1/payments/toss/success"
    fail_url: "http://localhost:8080/api/v1/payments/toss/fail"
    origin_url: "https://api.tosspayments.com/v1"

server:
  port: 8081

oauth:
  naver:
    client_id: "RVvWO7R3QM1UnNRS0fnv"
    redirect_uri: "http://127.0.0.1:8080/oauth/redirected/naver"
    client_secret: "fqXwPVg6rW"
    scope: name, email, mobile
