spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awseb-e-x8ii5dpdrm-stack-awsebrdsdatabase-wjvwop1fsrzo.cvgsgsx6gmpf.ap-northeast-2.rds.amazonaws.com:3306/ebdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

payment:
  toss:
    test_client_key: "test_ck_6BYq7GWPVv5DRddeYNn3NE5vbo1d"
    test_secret_key: "test_sk_eqRGgYO1r5qOd0v64nWrQnN2Eyaz"
    success_url: "http://127.0.0.1:8080/success.html"
    fail_url: "http://127.0.0.1:8080/fail.html"
    origin_url: "https://api.tosspayments.com/v1"

server:
  port: 5000

oauth:
  naver:
    client_id: "RVvWO7R3QM1UnNRS0fnv"
    redirect_uri: "http://127.0.0.1:8080/oauth/redirected/naver"
    client_secret: "fqXwPVg6rW"
    scope: name, email, mobile
