spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

payment:
  toss:
    test_client_key: test_ck_6BYq7GWPVv5DRddeYNn3NE5vbo1d
    test_secret_key: test_sk_eqRGgYO1r5qOd0v64nWrQnN2Eyaz
    success_url: "http://localhost:8080/api/v1/payments/toss/success"
    fail_url: "http://localhost:8080/api/v1/payments/toss/fail"
server:
  port: 8081
